# Generated by Django 5.0.6 on 2026-09-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemohub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('units', models.PositiveIntegerField()),
                ('hospital', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('needer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemohub.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('distance_km', models.FloatField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hemohub.loginuser')),
            ],
        ),
    ]
