# Generated by Django 5.0.6 on 2026-09-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemohub', '0002_bloodrequest_donorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('hospital', models.CharField(blank=True, max_length=150)),
                ('alert_type', models.CharField(default='Normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('donation_date', models.DateField()),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemohub.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemohub.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemohub.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemohub.loginuser')),
            ],
        ),
    ]
