# Generated by Django 5.0.6 on 2026-09-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemohub', '0003_alert_donation_donorresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='blood_request',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='donor',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
