# Generated by Django 5.0.6 on 2026-09-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemohub', '0005_donorprofile_last_donation_date_donorprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorresponse',
            name='blood_request',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='donor',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='DonationHistory',
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.DeleteModel(
            name='DonorProfile',
        ),
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
