# Generated by Django 5.0.6 on 2026-09-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemohub', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='needer',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='blood_request',
        ),
        migrations.RemoveField(
            model_name='suspiciousrequest',
            name='blood_request',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='donor',
        ),
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='SuspiciousRequest',
        ),
        migrations.DeleteModel(
            name='DonationHistory',
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.DeleteModel(
            name='DonorProfile',
        ),
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
